name: deploy

on:
    push:
        branches:
            - 'main' # 只针对 main 分支
        paths:
            - '.github/workflows/*'
            - 'src/**'
            - 'bin/*'
            - 'package.json'

jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.MY_ID_RSA}}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan 125.124.59.115 >> ~/.ssh/known_hosts
            - name: deploy # 部署
              run: |
                  ssh work@125.124.59.115 "
                    # 【注意】要提前 git clone 代码到 /root/myblog/imooc-320-server 目录

                    cd /root/myblog/imooc-320-server;
                    git checkout . ;
                    git checkout main;
                    git pull origin main; # 重新下载最新代码

                    # 启动服务
                    npm i;
                    npm run prd;
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa
